### ISSUE TITLE
运行的时候出现index溢出的错误

### ISSUE THREAD

**Issue by lvqiao490656285** [ChaoPei/caltech-voc-convert#1]
Traceback (most recent call last):
  File "./voc2007-converter/converter.py", line 96, in <module>
    create_voc(annos_json_path, src_img_path, dst_path, dataset_config)
  File "./voc2007-converter/converter.py", line 21, in create_voc
    train_annos, test_annos = parse(annos_json_path, dataset_config)
  File "/home/lvqiao/projects/faster-rcnn.pytorch-plan2/data/caltech-voc2007-converter-master/voc2007-converter/parse_annotations_json.py", line 64, in parse
    not dataset_config["reasonable_filter"](obj):
  File "/home/lvqiao/projects/faster-rcnn.pytorch-plan2/data/caltech-voc2007-converter-master/voc2007-converter/filter.py", line 73, in caltech_reasonable_filter
    visibility_filter(box)
  File "/home/lvqiao/projects/faster-rcnn.pytorch-plan2/data/caltech-voc2007-converter-master/voc2007-converter/filter.py", line 46, in visibility_filter
    visible_width = box['posv'][2]
IndexError: list index out of range

前面几步convert都成功运行了，就在这里报错了。

**Comment by murphypei** [comment]
@lvqiao490656285 我暂时手头还没有这个数据集，之前运行是没有问题的，我自己测过，等过几天我下载完整的数据集再测试一下，看看能不能复现你的错误
